menu:
    Blog: /
    Archive: /archives/
    Weibo:
    GitHub:
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: 

# Analytics
# google-analytics:
ga:

# Copyright Infomation
startyear: 2014

# Scheme
scheme: Artemis
